// source: ComputationMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.unit.ComputationRequest', null, global);
goog.exportSymbol('proto.unit.ComputationResponse', null, global);
goog.exportSymbol('proto.unit.ComputationResponse.DataCase', null, global);
goog.exportSymbol('proto.unit.ComputationResponse.StatusCode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.unit.ComputationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.unit.ComputationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.unit.ComputationRequest.displayName = 'proto.unit.ComputationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.unit.ComputationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.unit.ComputationResponse.oneofGroups_);
};
goog.inherits(proto.unit.ComputationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.unit.ComputationResponse.displayName = 'proto.unit.ComputationResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.unit.ComputationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.unit.ComputationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.unit.ComputationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.unit.ComputationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    startLayer: jspb.Message.getFieldWithDefault(msg, 1, 0),
    x: msg.getX_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.unit.ComputationRequest}
 */
proto.unit.ComputationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.unit.ComputationRequest;
  return proto.unit.ComputationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.unit.ComputationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.unit.ComputationRequest}
 */
proto.unit.ComputationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStartLayer(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setX(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.unit.ComputationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.unit.ComputationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.unit.ComputationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.unit.ComputationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartLayer();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getX_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional uint64 start_layer = 1;
 * @return {number}
 */
proto.unit.ComputationRequest.prototype.getStartLayer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.unit.ComputationRequest} returns this
 */
proto.unit.ComputationRequest.prototype.setStartLayer = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes x = 2;
 * @return {!(string|Uint8Array)}
 */
proto.unit.ComputationRequest.prototype.getX = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes x = 2;
 * This is a type-conversion wrapper around `getX()`
 * @return {string}
 */
proto.unit.ComputationRequest.prototype.getX_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getX()));
};


/**
 * optional bytes x = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getX()`
 * @return {!Uint8Array}
 */
proto.unit.ComputationRequest.prototype.getX_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getX()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.unit.ComputationRequest} returns this
 */
proto.unit.ComputationRequest.prototype.setX = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.unit.ComputationResponse.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.unit.ComputationResponse.DataCase = {
  DATA_NOT_SET: 0,
  ERROR_MESSAGE: 2,
  RESULT: 3,
  NEXT_REQUEST: 4
};

/**
 * @return {proto.unit.ComputationResponse.DataCase}
 */
proto.unit.ComputationResponse.prototype.getDataCase = function() {
  return /** @type {proto.unit.ComputationResponse.DataCase} */(jspb.Message.computeOneofCase(this, proto.unit.ComputationResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.unit.ComputationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.unit.ComputationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.unit.ComputationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.unit.ComputationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorMessage: jspb.Message.getFieldWithDefault(msg, 2, ""),
    result: msg.getResult_asB64(),
    nextRequest: (f = msg.getNextRequest()) && proto.unit.ComputationRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.unit.ComputationResponse}
 */
proto.unit.ComputationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.unit.ComputationResponse;
  return proto.unit.ComputationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.unit.ComputationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.unit.ComputationResponse}
 */
proto.unit.ComputationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.unit.ComputationResponse.StatusCode} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setResult(value);
      break;
    case 4:
      var value = new proto.unit.ComputationRequest;
      reader.readMessage(value,proto.unit.ComputationRequest.deserializeBinaryFromReader);
      msg.setNextRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.unit.ComputationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.unit.ComputationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.unit.ComputationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.unit.ComputationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getNextRequest();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.unit.ComputationRequest.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.unit.ComputationResponse.StatusCode = {
  ERROR: 0,
  SUCCESS: 1,
  NOT_SUCCESS: 2
};

/**
 * optional StatusCode status = 1;
 * @return {!proto.unit.ComputationResponse.StatusCode}
 */
proto.unit.ComputationResponse.prototype.getStatus = function() {
  return /** @type {!proto.unit.ComputationResponse.StatusCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.unit.ComputationResponse.StatusCode} value
 * @return {!proto.unit.ComputationResponse} returns this
 */
proto.unit.ComputationResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string error_message = 2;
 * @return {string}
 */
proto.unit.ComputationResponse.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.unit.ComputationResponse} returns this
 */
proto.unit.ComputationResponse.prototype.setErrorMessage = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.unit.ComputationResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.unit.ComputationResponse} returns this
 */
proto.unit.ComputationResponse.prototype.clearErrorMessage = function() {
  return jspb.Message.setOneofField(this, 2, proto.unit.ComputationResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.unit.ComputationResponse.prototype.hasErrorMessage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes result = 3;
 * @return {!(string|Uint8Array)}
 */
proto.unit.ComputationResponse.prototype.getResult = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes result = 3;
 * This is a type-conversion wrapper around `getResult()`
 * @return {string}
 */
proto.unit.ComputationResponse.prototype.getResult_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getResult()));
};


/**
 * optional bytes result = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getResult()`
 * @return {!Uint8Array}
 */
proto.unit.ComputationResponse.prototype.getResult_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getResult()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.unit.ComputationResponse} returns this
 */
proto.unit.ComputationResponse.prototype.setResult = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.unit.ComputationResponse.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.unit.ComputationResponse} returns this
 */
proto.unit.ComputationResponse.prototype.clearResult = function() {
  return jspb.Message.setOneofField(this, 3, proto.unit.ComputationResponse.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.unit.ComputationResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ComputationRequest next_request = 4;
 * @return {?proto.unit.ComputationRequest}
 */
proto.unit.ComputationResponse.prototype.getNextRequest = function() {
  return /** @type{?proto.unit.ComputationRequest} */ (
    jspb.Message.getWrapperField(this, proto.unit.ComputationRequest, 4));
};


/**
 * @param {?proto.unit.ComputationRequest|undefined} value
 * @return {!proto.unit.ComputationResponse} returns this
*/
proto.unit.ComputationResponse.prototype.setNextRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.unit.ComputationResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.unit.ComputationResponse} returns this
 */
proto.unit.ComputationResponse.prototype.clearNextRequest = function() {
  return this.setNextRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.unit.ComputationResponse.prototype.hasNextRequest = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.unit);
