# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ComputationMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ComputationMessage.proto',
  package='unit',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x43omputationMessage.proto\x12\x04unit\"4\n\x12\x43omputationRequest\x12\x13\n\x0bstart_layer\x18\x01 \x01(\x04\x12\t\n\x01x\x18\x02 \x01(\x0c\"\xe7\x01\n\x13\x43omputationResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.unit.ComputationResponse.StatusCode\x12\x17\n\rerror_message\x18\x02 \x01(\tH\x00\x12\x10\n\x06result\x18\x03 \x01(\x0cH\x00\x12\x30\n\x0cnext_request\x18\x04 \x01(\x0b\x32\x18.unit.ComputationRequestH\x00\"5\n\nStatusCode\x12\t\n\x05\x45RROR\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bNOT_SUCCESS\x10\x02\x42\x06\n\x04\x64\x61tab\x06proto3'
)



_COMPUTATIONRESPONSE_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='unit.ComputationResponse.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_SUCCESS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=259,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_COMPUTATIONRESPONSE_STATUSCODE)


_COMPUTATIONREQUEST = _descriptor.Descriptor(
  name='ComputationRequest',
  full_name='unit.ComputationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_layer', full_name='unit.ComputationRequest.start_layer', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='unit.ComputationRequest.x', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=86,
)


_COMPUTATIONRESPONSE = _descriptor.Descriptor(
  name='ComputationResponse',
  full_name='unit.ComputationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='unit.ComputationResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='unit.ComputationResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='unit.ComputationResponse.result', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_request', full_name='unit.ComputationResponse.next_request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPUTATIONRESPONSE_STATUSCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='unit.ComputationResponse.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=89,
  serialized_end=320,
)

_COMPUTATIONRESPONSE.fields_by_name['status'].enum_type = _COMPUTATIONRESPONSE_STATUSCODE
_COMPUTATIONRESPONSE.fields_by_name['next_request'].message_type = _COMPUTATIONREQUEST
_COMPUTATIONRESPONSE_STATUSCODE.containing_type = _COMPUTATIONRESPONSE
_COMPUTATIONRESPONSE.oneofs_by_name['data'].fields.append(
  _COMPUTATIONRESPONSE.fields_by_name['error_message'])
_COMPUTATIONRESPONSE.fields_by_name['error_message'].containing_oneof = _COMPUTATIONRESPONSE.oneofs_by_name['data']
_COMPUTATIONRESPONSE.oneofs_by_name['data'].fields.append(
  _COMPUTATIONRESPONSE.fields_by_name['result'])
_COMPUTATIONRESPONSE.fields_by_name['result'].containing_oneof = _COMPUTATIONRESPONSE.oneofs_by_name['data']
_COMPUTATIONRESPONSE.oneofs_by_name['data'].fields.append(
  _COMPUTATIONRESPONSE.fields_by_name['next_request'])
_COMPUTATIONRESPONSE.fields_by_name['next_request'].containing_oneof = _COMPUTATIONRESPONSE.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['ComputationRequest'] = _COMPUTATIONREQUEST
DESCRIPTOR.message_types_by_name['ComputationResponse'] = _COMPUTATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputationRequest = _reflection.GeneratedProtocolMessageType('ComputationRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONREQUEST,
  '__module__' : 'ComputationMessage_pb2'
  # @@protoc_insertion_point(class_scope:unit.ComputationRequest)
  })
_sym_db.RegisterMessage(ComputationRequest)

ComputationResponse = _reflection.GeneratedProtocolMessageType('ComputationResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONRESPONSE,
  '__module__' : 'ComputationMessage_pb2'
  # @@protoc_insertion_point(class_scope:unit.ComputationResponse)
  })
_sym_db.RegisterMessage(ComputationResponse)


# @@protoc_insertion_point(module_scope)
