# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransmissionMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransmissionMessage.proto',
  package='unit',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19TransmissionMessage.proto\x12\x04unit\"\x10\n\x0eQlengthRequest\"\"\n\x0fQlengthResponse\x12\x0f\n\x07Qlength\x18\x01 \x01(\x04\x62\x06proto3'
)




_QLENGTHREQUEST = _descriptor.Descriptor(
  name='QlengthRequest',
  full_name='unit.QlengthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=51,
)


_QLENGTHRESPONSE = _descriptor.Descriptor(
  name='QlengthResponse',
  full_name='unit.QlengthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Qlength', full_name='unit.QlengthResponse.Qlength', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['QlengthRequest'] = _QLENGTHREQUEST
DESCRIPTOR.message_types_by_name['QlengthResponse'] = _QLENGTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QlengthRequest = _reflection.GeneratedProtocolMessageType('QlengthRequest', (_message.Message,), {
  'DESCRIPTOR' : _QLENGTHREQUEST,
  '__module__' : 'TransmissionMessage_pb2'
  # @@protoc_insertion_point(class_scope:unit.QlengthRequest)
  })
_sym_db.RegisterMessage(QlengthRequest)

QlengthResponse = _reflection.GeneratedProtocolMessageType('QlengthResponse', (_message.Message,), {
  'DESCRIPTOR' : _QLENGTHRESPONSE,
  '__module__' : 'TransmissionMessage_pb2'
  # @@protoc_insertion_point(class_scope:unit.QlengthResponse)
  })
_sym_db.RegisterMessage(QlengthResponse)


# @@protoc_insertion_point(module_scope)
