#!/bin/bash

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-spec dnet-computationunit-manifest.yaml
./manifest-tool push from-spec dnet-transmissionunit-manifest.yaml