apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnet-computationunit-10
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnet-computationunit-10
  template:
    metadata:
      name: dnet-computationunit-10-pod
      labels:
        app: dnet-computationunit-10
    spec:
      containers:
        - name: dnet-computationunit
          image: yindaheng98/dnet-computationunit
          command: ["python"]
          args:
            - "ComputationUnit"
            - "-a"
            - "dnet-unit-10"
            - "-e"
            - "10"
