apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnet-transmissionunit-16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnet-transmissionunit-16
  template:
    metadata:
      name: dnet-transmissionunit-16-pod
      labels:
        app: dnet-transmissionunit-16
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingRequiredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: dnet-role
                  operator: In
                  values:
                    - cloud
      containers:
        - name: dnet-transmissionunit
          image: yindaheng98/dnet-transmissionunit
          ports:
            - containerPort: 8080
          command: ["npm"]
          args:
            - "run"
            - "start"
        - name: dnet-middleware
          image: rabbitmq:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: dnet-unit-16
spec:
  selector:
    app: dnet-transmissionunit-16
  ports:
  - name: dnet-transmissionunit
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: dnet-queue
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: dnet-queue-web
    protocol: TCP
    port: 15672
    targetPort: 15672
