apiVersion: v1
kind: Service
metadata:
  name: dnet
spec:
  type: NodePort
  selector:
    app: dnet-transmissionunit-10
  ports:
  - name: dnet-transmissionunit
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000